---
- name: "Install epel repository for RHEL & Centos"
  package:
    name: "epel-release"
    state: "present"
  become: True
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution != 'Fedora'

- name: "Enable PowerTools repository"
  import_role:
    name: robertdebock.powertools
  become: True

- name: "Install common packages for RHEL & Centos"
  yum:
    name: "{{ common_packages }}"
    state: "present"
    update_cache: True
  become: True
  when: ansible_os_family == "RedHat"

- name: "Install common packages for Debian & Ubuntu"
  apt:
    name: "{{ common_packages }}"
    state: "present"
    update_cache: True
  become: True
  when: ansible_os_family == "Debian"

- name: "Remove dhclient"
  package:
    name: "dhclient"
    state: "absent"
  become: True
  when: remove_dhclient | bool

- name: "Remove fwupd"
  package:
    name: "fwupd"
    state: "absent"
  become: True
  when: remove_fwupd | bool

- name: "Remove qemu-guest-agent"
  package:
    name: "qemu-guest-agent "
    state: "absent"
  become: True
  when: remove_qemu_guest_agent | bool
