---
- name: "Install epel repository for RHEL & Centos"
  package:
    name: "epel-release"
    state: present
  become: True
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution != 'Fedora'

- name: "Enable PowerTools rpository for RHEL8 & Centos8"
  yum_repository:
    name: "PowerTools"
    description: "CentOS-$releasever - PowerTools"
    file: "CentOS-PowerTools"
    mirrorlist: "http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=PowerTools&infra=$infra"
    gpgcheck: yes
    gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial"
    enabled: yes
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution == "Fedora" or ansible_distribution_major_version == "8"

- name: "Install common packages for RHEL & Centos (< 8)"
  package:
    name: "{{ common_packages_redhat }}"
    state: present
  become: True
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version < "8"
    - ansible_distribution != 'Fedora'

- name: "Install common packages for Fedora & RHEL & Centos (== 8)"
  package:
    name: "{{ common_packages_fedora }}"
    state: present
  become: True
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution == "Fedora" or ansible_distribution_major_version == "8"

- name: "Install aptitude for Debian & Ubuntu"
  package:
    name: "aptitude"
    state: present
  become: True
  when: ansible_os_family == "Debian"

- name: "Install common packages for Debian & Ubuntu"
  package:
    name: "{{ common_packages_debian }}"
    state: present
  become: True
  when: ansible_os_family == "Debian"

