---
# tasks file for common

- name: Remove cloud-init
  import_tasks: remove_cloudinit.yml
  tags: cloudinit

- name: Update whole system
  import_tasks: update_system.yml
  when: update_system|bool
  tags: update

- name: Install common packages
  import_tasks: common_pkgs.yml
  tags: common_pkgs

- name: Setup unlimited bash history for root
  import_tasks: unlimited_bash_history.yml
  tags: unlimited_bash_history

#- name: Apply security settings
#  import_tasks: security.yml
#  tags: security

- name: Configure DNS resolvers in /etc/resolv.conf
  import_role:
    name: jdauphant.dns
  vars:
    ansible_become: True
    dns_forced_in_dhclientconf: False
  when: configure_dns_resolvers
  tags: resolvers

#- name: Install & configure firewalld
#  import_role:
#    name: elcomtik.firewalld
#  when: firewall_enabled
#  tags: firewall

#- name: Install & configure fail2ban
#  import_tasks: fail2ban.yml
#  when: firewall_enabled and fail2ban_enabled
#  tags: fail2ban

- name: Install & configure etckeeper
  import_role:
    name: elcomtik.etckeeper
  tags: etckeeper
