---
- name: Add variables to /root/.bashrc
  blockinfile: 
    dest: "/root/.bashrc"
    backup: true
    insertafter: EOF
    block: |
      HISTFILESIZE=400000000
      HISTSIZE=10000
      PROMPT_COMMAND="history -a"
      export HISTTIMEFORMAT="%d/%m/%y %T"
      shopt -s histappend
  become: true

- name: Set ACL to appendonly on file /root/.bash_history 
  file:
    path: "/root/.bash_history"
    attributes: ae
    modification_time: preserve
    access_time: preserve
  become: true
